#Change makefile to point to right zLib directories.

x32:	make -f win32/Makefile.gcc

x64: 	make -f win32/Makefile.gcc

both:
	cp -iv zlib1.dll C:/Users/Brandon/Desktop/zlib/bin
	cp -iv zconf.h zlib.h C:/Users/Brandon/Desktop/zlib/include
	cp -iv libz.a libz.dll.a C:/Users/Brandon/Desktop/zlib/lib